name: Makefile CI

on:
  push:
    branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2" ]
  pull_request:
    branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2" ]

jobs:
  build-Go:

      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.19.5

        - name: Build
          working-directory: cmd
          run: go build -v ./...

        - name: Test
          run: go test -v ./...
  build-Docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Package Registry
        run: echo "${{ secrets.CONTAINERREGISTRY_GITHUB_ACCESSTOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.CONTAINERREGISTRY_GITHUB_USERNAME }}" --password-stdin
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: HWRAIO/backend:latest
