name: Makefile CI

on:
  push:
    branches: [ "main", "dev", "HAIO-91_Dockerfile_config" ]
  pull_request:
    branches: [ "main", "dev", "HAIO-91_Dockerfile_config" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Package Registry
        run: echo "${{ secrets.CONTAINERREGISTRY_GITHUB_ACCESSTOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.CONTAINERREGISTRY_GITHUB_USERNAME }}" --password-stdin
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
