name: Update Version File

on:
  push:
    branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2", "feature/HAIO-96/CI_CD_einrichten_BE-2_Test" ]
  pull_request:
    branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2", "feature/HAIO-96/CI_CD_einrichten_BE-2_Test" ]
    types: [closed]

jobs:
  read:

    runs-on: ubuntu-latest
    #if: |
    #  github.event.pull_request.merged
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.json
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"