name: Makefile CI

# Vars:
# DEV_BRANCH = feature/HAIO-96/CI_CD_einrichten_BE-2_Test

on:
  #push:
  #  branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2" ]
  #  tags:
  #    - 'v*'
  pull_request:
    branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2", "feature/HAIO-96/CI_CD_einrichten_BE-2_Test" ]
    types: [closed]

jobs:
  build-Docker:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged

    steps:
      - 
        name: Branchname
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo HEAD_REF: $GITHUB_HEAD_REF
          echo BASE_REF: $GITHUB_BASE_REF
          echo dev: ${{vars.DEV_BRANCH}}
        # example for $GITHUB_HEAD_REF and $GITHUB_BASE_REF:
        # When you merge from "feature/HAIO-96/CI_CD_einrichten_BE-2" to "feature/HAIO-96/CI_CD_einrichten_BE-2_Test"
        # HEAD_REF: feature/HAIO-96/CI_CD_einrichten_BE-2
        # BASE_REF: feature/HAIO-96/CI_CD_einrichten_BE-2_Test
      -
        name: Checkout
        uses: actions/checkout@v3