name: Makefile CI

on:
  push:
    branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "dev", "feature/HAIO-96/CI_CD_einrichten_BE-2" ]

jobs:    
  build-Docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: versiontag
        id: semver-tag
        uses: gandarez/semver-action@v1
        with:
          prefix: ""
          prerelease_id: "alpha"
          main_branch_name: "main"
          develop_branch_name: "dev"
          debug: "false"
      - name: "Created tag"
        run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"

      - 
        name: Branchname
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/hwr-all-in-one/backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
